#name: Payhere debug CI
#
#on:
#  push:
#    tags:
#      - DEBUG_*
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin' # See 'Supported distributions' for available options
#          java-version: '11'
#
#      - name: Set VAN from tag name env
#        run: echo DEV_VAN=${RELEASE_VAN} >> ./signing.properties
#        env:
#          RELEASE_VAN: ${GITHUB_REF_NAME:6}
#
#      - name: Decode Keystore
#        run: echo $SIGNING_KEY | base64 -di > payhere_cat_key.keystore
#        env:
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#
#      - name: change keystore path
#        run: mv payhere_cat_key.keystore ./payhereCat/payhere_cat_key.keystore
#
#      - name: update store file from secret
#        run: echo RELEASE_STORE_FILE="$RELEASE_STORE_FILE" > ./signing.properties
#        env:
#          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
#
#      - name: update store alias from secret
#        run: echo RELEASE_KEY_ALIAS="$RELEASE_KEY_ALIAS" >> ./signing.properties
#        env:
#          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
#
#      - name: update store password from secret
#        run: echo RELEASE_STORE_PASSWORD="$RELEASE_STORE_PASSWORD" >> ./signing.properties
#        env:
#          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
#
#      - name: update key password from secret
#        run: echo RELEASE_KEY_PASSWORD="$RELEASE_KEY_PASSWORD" >> ./signing.properties
#        env:
#          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
#
#      - name: update appguard app key from secret
#        run: echo APPGUARD_APP_KEY="APPGUARD_APP_KEY" >> ./signing.properties
#        env:
#          APPGUARD_APP_KEY: ${{ secrets.APPGUARD_APP_KEY }}
#
#      - name: Build with Gradle
#        run: bash ./gradlew assembleDevDebug
#
#      - name: Set van to env from tag name
#        run: echo "DEVELOP_VERSION=${GITHUB_REF_NAME:6}" >> $GITHUB_ENV
#
#      - name: check tag name
#        run: |
#          echo $DEVELOP_VERSION
#          echo ${{ env.DEVELOP_VERSION }}
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ env.DEVELOP_VERSION }}
#          path: app/build/outputs/apk/dev/debug/PAYHERE_CAT_${{ env.RELEASE_VAN }}_*.apk
#
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_CHANNEL: notify_android-build
#          SLACK_COLOR: '#00AA00'
#          SLACK_MESSAGE: '${{ env.RELEASE_VAN }} 개발 빌드가 완료되었습니다'
#          SLACK_TITLE: '${{ env.RELEASE_VAN }} 개발버전 입니다.'
#          SLACK_USERNAME: 개발계 디버그 (PPN 재서명 필요 X)
#          SLACK_WEBHOOK: ${{ secrets.ANDROID_BUILD }}
#          SLACK_FOOTER: 개발버전 입니다.
