name: Remove old artifacts

on:
  schedule:
    - cron: '0 4 * * 0'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove artifacts
        uses: c-hive/gha-remove-artifacts@v1.3.0
        with:
          age: '1 weeks'
          skip-tags: true
